[package]
name = "step-broadcastooor"
version = "0.1.0"
authors = ["Dana <dana@step.finance>"]
repository = "https://github.com/step-finance/step-broadcastooor"
homepage = "https://step.finance/"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
log = "0.4.14"
env_logger = "0.10.1"
futures-util = "0.3.19"
anyhow = "1.0.79"
serde_json = "1.0.108"
serde = "1.0.193"
axum = "0.7.4"
http = "1.1.0"
evalexpr = { version = "11.3.0", features = [] }
dashmap = "5.5.3"
tower-http = { version = "0.5.2", features = ["cors"] }
socketioxide = { version = "0.11.0", features = [
    "extensions",
    "state",
    "tracing",
] }
clap = { version = "3.2.23", features = ["derive", "env"] }
tokio = { version = "1.35.1", features = [
    "time",
    "macros",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
] }
ts-rs = { version = "8.1", features = ["chrono-impl"] }
metrics_cloudwatch = "2.0.1"

step-common-rust = { git = "ssh://git@github.com/step-finance/step-common-rust", tag = "0.1.2", version = "0.1.2" }
step-ingestooor-engine = { git = "ssh://git@github.com/step-finance/step-ingestooor.git", rev = "f759c9db793962e2c7a483bc866fea7a0e209db6" }
step-ingestooor-sdk = { git = "ssh://git@github.com/step-finance/step-ingestooor.git", rev = "f759c9db793962e2c7a483bc866fea7a0e209db6" }

# step-common-rust = { path = "../step-common-rust" }
# step-ingestooor-engine = { path = "../step-ingestooor/crates/engine" }
# step-ingestooor-sdk = { path = "../step-ingestooor/crates/sdk" }

indexer_rabbitmq = { package = "holaplex-indexer-rabbitmq", git = "https://github.com/step-finance/indexer-geyser-plugin", rev = "10fdb0ca1cc402ca614dba7cff7e06ef87768f62" }

[patch.crates-io]
solana-client = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
solana-transaction-status = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
solana-sdk = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
solana-logger = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
solana-program = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
solana-metrics = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
solana-account-decoder = { git = 'https://github.com/step-finance/solana.git', rev = "2cfca0222c46c46fce886061b4027f7133170aa0" }
